### ISSUE TITLE
Private constructors

### ISSUE THREAD

**Issue by AbuJunayd** [naneau/php-obfuscator#10]
I have some classes with private constructors and after running the obfuscator the constructor function is being renamed from __construct to sp29fb99

The construction mechanism is then broken.

**Comment by AbuJunayd** [comment]
In ScramblePrivateMethod.php I have added this condition in scanMethodDefinitions()
strpos($node->name, '__') !== 0
to avoid scrambling any magic method

**Comment by naneau** [comment]
@AbuJunayd that seems like a good fix, I'll implement that.

**Comment by naneau** [comment]
I might make this more generic by adding regex ignores (and have a default one for `__` methods), combining this with #17
