### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by bobalazek** [naneau/php-obfuscator#11]
Is there any possibility to ignore stripping out code blocks with annotations?

**Comment by naneau** [comment]
@bobalazek I think we are limited by the parser here. I will check this.

**Comment by bobalazek** [comment]
Ok, thanks!

Yeah, would be nice, because many Symfony2 stuff depends on Annotations.

**Comment by naneau** [comment]
Do note that annotations might not work well (or at all) if your method parameters are scrambled. You may have to disable that scrambler.

**Comment by bobalazek** [comment]
Yeah, you are right here. Haven't thought about that at all.

The more logical step in this case may rather be exclusion (#9).
