### ISSUE TITLE
Obfuscates methods attached to other objects when the class has the same named method.

### ISSUE THREAD

**Issue by salarelv** [naneau/php-obfuscator#14]
private function getLanguages(){
   return $this->getApplication()->getLanguages(); //this is a public function
}

-----

private function HASH(){
   return $this->getApplication()->HASH();
}

**Comment by naneau** [comment]
This is a known shortcoming, there is no way of detecting whether a method call is on `$this` (or something that chains into `$this`), or another object just by looking at the AST. You'll have to add these methods to the ignore list.
