### ISSUE TITLE
does not work on php 5.3

### ISSUE THREAD

**Issue by pk-fr** [naneau/php-obfuscator#16]
inconsistency between README.md and real behaviour.

with php 5.3, I have the following error:
PHP Parse error:  syntax error, unexpected T_USE, expecting T_FUNCTION in /usr/local/php-obfuscator/src/Naneau/Obfuscator/Node/Visitor/ScramblePrivateMethod.php on line 45

it works ok on php 5.5

according README.md :
It is compatible with PHP up to and including 5.5.

any plans for php 5.6 or php 7 ?

**Comment by naneau** [comment]
It should work with PHP 5.3 and up. Is there an issue with the code you are parsing perhaps?

**Comment by pk-fr** [comment]
the same code parsing works ok on php 5.5 ... 
so I don't know....

**Comment by pk-fr** [comment]
/usr/local/php-obfuscator/src/Naneau/Obfuscator/Node/Visitor/ScramblePrivateMethod.php line 45 is:
    use TrackingRenamerTrait;

Traits are implemented in php since 5.4 .....

**Comment by naneau** [comment]
Ah, you are right, that completely slipped my mind. I'll have to make that clear in the README. It will of course still obfuscate PHP 5.3 code just fine, but it will need to run on a current PHP release.

**Comment by naneau** [comment]
Made clear in b5c48b51312abbaa5be8977886bf420fefcb077e
