### ISSUE TITLE
Error while obfuscate a bigger project

### ISSUE THREAD

**Issue by nasinasi** [naneau/php-obfuscator#2]
Hi, with some php-files I got this error:
Obfuscating stage/interfaces/formAPI.php
testPHP Warning:  strlen() expects parameter 1 to be string, object given in /root/obfuscator/php-obfuscator-master/src/Naneau/Obfuscator/Node/Visitor/Scrambler.php on line 67
PHP Catchable fatal error:  Object of class PhpParser\Node\Expr\ArrayDimFetch could not be converted to string in /root/obfuscator/php-obfuscator-master/src/Naneau/Obfuscator/StringScrambler.php on line 53

and it crashed. I had a look to the code (StringScrambler) and I try to catch the error, but it seams like, that now some variables are not right referenced. Any idea, what to do with this?

    protected function scramble(Node $node, $var = 'name')
    {
        // String/value to scramble
        $toScramble = $node->$var;
        if(is_object($toScramble))
           return $node;
        // Make sure there's something to scramble
        if (strlen($toScramble) === 0) {
            throw new InvalidArgumentException(sprintf(
                '"%s" value empty for node, can not scramble',
                $var
            ));
        }

        // Should we ignore it?
        if (in_array($toScramble, $this->getIgnore())) {
            return $node;
        }

        // Prefix with 'p' so we dont' start with an number
        $node->$var = $this->scrambleString($toScramble);

        // Return the node
        return $node;
    }

Thanks,
Nerd

**Comment by naneau** [comment]
@pirackr a PR is always welcome, although I think that we'd be better off with a guard around the `strlen()`.

**Comment by pirackr** [comment]
@naneau : I just pushed my PR, I think it fixed this issue.

**Comment by naneau** [comment]
@pirackr confirmed, I think that fixes this and #6
