### ISSUE TITLE
Live Demo ?

### ISSUE THREAD

**Issue by darkcyber** [naneau/php-obfuscator#20]
Hello, can i use this to obfuscate my php code ? then run it without any loader like Zend or IonCube.

Let's say simple PHP code like this ?

<?php

function hello(){
$hello = "This Is Hello";
return $hello;
}

hello();

?>

Can this script obfuscated and can i run without any loader ? 
Or any live demo ? 
thanks in advance.

**Comment by naneau** [comment]
Yes, that is exactly what this should accomplish. Do note that this is more of an experiment in its current state, and there are certain constructs it can not support. For most code it should work no problem though.
