### ISSUE TITLE
Can you include png, js, css, & html compression before the obfuscation?

### ISSUE THREAD

**Issue by ruvenss** [naneau/php-obfuscator#25]
That way the output code will save band and the size of the files tpl, html, js and etc will be optimised for the browser.

I will be interesting that it does it inside the the strings like "<table> <tr>BLA BLA..." that  the final code will be at least.

It will certainly make the whole package really really interesting it will be 1 step solution.

**Comment by naneau** [comment]
I think that's outside of the scope of this project, there are plenty of great build tools out there (such as Gulp) that can do this for you. This package follows the UNIX philosophy of only doing one thing.
