### ISSUE TITLE
[Feature request] Grunt version of your obfuscator

### ISSUE THREAD

**Issue by tatsen** [naneau/php-obfuscator#37]
It would be great to have a grunt version of your obfuscator. 

In one of my projects i'm using grunt to build a WordPress plug-in. The only step which is not really "gruntified" is the obfuscation of the code. As a workaround I'm using the grunt-exec module but it would be great to have your obfuscator as a "native" grunt plug-in.

I don't want to use the grunt-hazy module (another obfuscator) since i really appreciate the great work you've put in this project.

**Comment by naneau** [comment]
I don't think that's really within the scope of this project, but I can see how it would be useful as a side project.

Grunt hazy is a base-64 encoder, it doesn't function in the same way as this project.
