### ISSUE TITLE
[Feature request] adding string obfuscation

### ISSUE THREAD

**Issue by CaledoniaProject** [naneau/php-obfuscator#39]
Can you "encode" all strings constants as well?

**Comment by naneau** [comment]
Wouldn't that rather get in the way of functionality? Strings contain actual values with meaning to your application, hashing them would render them meaningless.

**Comment by CaledoniaProject** [comment]
I meant something that decrypts strings at runtime, only encrypted strings are stored in source files.

**Comment by naneau** [comment]
I feel that would be outside the scope of this project. You'd need a separate component that can do this at runtime, which would need to be very performant. The keys to decrypt strings would also need to be provided alongside the code, or the tool wouldn't be able to work. I don't think it would add much in the way of security, but it would come at a great cost.
