### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by RobinTail** [naneau/php-obfuscator#40]
Hello. 
I'd like to use Obfuscator in my project build, but sometimes user reports me that he got a PHP error/notice. This information goes with file name and the line number. I suppose that it will be very difficult to associate obfuscated PHP statement with original PHP statement without any Source Map. 

Is there any ability to produce Source Map files? May be something like this JSON:

``
[{
  "source": {
    "line": 410,
    "code": "$data['length']"
  },
  "obfuscated": {
    "line": 15,
    "code": "$sp216f0c['length']"
  }
}, ... ]
``

**Comment by naneau** [comment]
I think you're right in saying that it would be fairly difficult to produce these. It may be somewhat easier to create a map of obfuscated name to original name for functions and the like, which may help in debugging, since we definitely do have both at some point.
