### ISSUE TITLE
Scramble variable not working as expected?

### ISSUE THREAD

**Issue by codex-corp** [naneau/php-obfuscator#5]
Hi,

in (ScrambleVariable) it does not define the variable which already renamed in rename array

it should be like this ?
https://gist.github.com/codex-corp/a1646c14b1b1fd02cc09

**Comment by naneau** [comment]
@codex-corp if you send it as a PR I'd be happy to take a look.

**Comment by codex-corp** [comment]
okay no problem! , btw i working on big project for php code protection if you are intersted i can give you close look .
